//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperZTP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperZTP.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj notatkę.
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 Dodaj notatkę.
        /// </summary>
        public static string AddNoteButton {
            get {
                return ResourceManager.GetString("AddNoteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zadanie.
        /// </summary>
        public static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Dodaj zadanie.
        /// </summary>
        public static string AddTaskButton {
            get {
                return ResourceManager.GetString("AddTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-Z.
        /// </summary>
        public static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastosuj filtry.
        /// </summary>
        public static string ApplyFilters {
            get {
                return ResourceManager.GetString("ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie zadaniami i notatkami.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalendarz.
        /// </summary>
        public static string CalendarTitle {
            get {
                return ResourceManager.GetString("CalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria:.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż ukończone.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonane zadania:.
        /// </summary>
        public static string CompletedTasksTitle {
            get {
                return ResourceManager.GetString("CompletedTasksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Względem daty ↑.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-Z Względem daty ↑.
        /// </summary>
        public static string DateAZ {
            get {
                return ResourceManager.GetString("DateAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-A Względem daty ↓.
        /// </summary>
        public static string DateZA {
            get {
                return ResourceManager.GetString("DateZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin:.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domyślny.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukończone.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj notatkę.
        /// </summary>
        public static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj zadanie.
        /// </summary>
        public static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtry.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generowanie.
        /// </summary>
        public static string GenerateFile {
            get {
                return ResourceManager.GetString("GenerateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupuj kategoriami.
        /// </summary>
        public static string GroupByCategory {
            get {
                return ResourceManager.GetString("GroupByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupuj tagami.
        /// </summary>
        public static string GroupByTag {
            get {
                return ResourceManager.GetString("GroupByTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcje grupowania:.
        /// </summary>
        public static string GroupingOptions {
            get {
                return ResourceManager.GetString("GroupingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodano notatkę: {0}.
        /// </summary>
        public static string HisAddNote {
            get {
                return ResourceManager.GetString("HisAddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodanie notatki nie powiodło się..
        /// </summary>
        public static string HisAddNoteFailed {
            get {
                return ResourceManager.GetString("HisAddNoteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodano zadanie: {0}.
        /// </summary>
        public static string HisAddTask {
            get {
                return ResourceManager.GetString("HisAddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodanie zadania nie powiodło się..
        /// </summary>
        public static string HisAddTaskFailed {
            get {
                return ResourceManager.GetString("HisAddTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięto notatkę: {0}.
        /// </summary>
        public static string HisDeleteNote {
            get {
                return ResourceManager.GetString("HisDeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięcie notatki nie powiodło się..
        /// </summary>
        public static string HisDeleteNoteFailed {
            get {
                return ResourceManager.GetString("HisDeleteNoteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięto zadanie: {0}.
        /// </summary>
        public static string HisDeleteTask {
            get {
                return ResourceManager.GetString("HisDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięcie zadanie nie powiodło się..
        /// </summary>
        public static string HisDeleteTaskFailed {
            get {
                return ResourceManager.GetString("HisDeleteTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zedytowano notatkę: {0}.
        /// </summary>
        public static string HisEditNote {
            get {
                return ResourceManager.GetString("HisEditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja notatki nie powiodła się..
        /// </summary>
        public static string HisEditNoteFailed {
            get {
                return ResourceManager.GetString("HisEditNoteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zedytowano zadanie: {0}.
        /// </summary>
        public static string HisEditTask {
            get {
                return ResourceManager.GetString("HisEditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja zadania nie powiodła się..
        /// </summary>
        public static string HisEditTaskFailed {
            get {
                return ResourceManager.GetString("HisEditTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia operacji.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string IsDone {
            get {
                return ResourceManager.GetString("IsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista zadań oraz notatek.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak grupowania.
        /// </summary>
        public static string NoGroup {
            get {
                return ResourceManager.GetString("NoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutaj wyświetlą się szczegóły wybranej notatki..
        /// </summary>
        public static string NoNoteSelected {
            get {
                return ResourceManager.GetString("NoNoteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutaj wyświetlą się szczegóły wybranego zadania..
        /// </summary>
        public static string NoTaskSelected {
            get {
                return ResourceManager.GetString("NoTaskSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż nieukończone.
        /// </summary>
        public static string NotCompleted {
            get {
                return ResourceManager.GetString("NotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 Notatki.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inne.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaległe zadania:.
        /// </summary>
        public static string OverdueTasksTitle {
            get {
                return ResourceManager.GetString("OverdueTasksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysoki.
        /// </summary>
        public static string PHigh {
            get {
                return ResourceManager.GetString("PHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niski.
        /// </summary>
        public static string PLow {
            get {
                return ResourceManager.GetString("PLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średni.
        /// </summary>
        public static string PMedium {
            get {
                return ResourceManager.GetString("PMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorytet:.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorytet ↑ (Wysoki -&gt; Niski).
        /// </summary>
        public static string PriorityHighToLow {
            get {
                return ResourceManager.GetString("PriorityHighToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorytet ↓ (Niski -&gt; Wysoki).
        /// </summary>
        public static string PriorityLowToHigh {
            get {
                return ResourceManager.GetString("PriorityLowToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losowa kolejność.
        /// </summary>
        public static string RandomOrder {
            get {
                return ResourceManager.GetString("RandomOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport.
        /// </summary>
        public static string Raport {
            get {
                return ResourceManager.GetString("Raport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygenerowano raport w formacie {0}.
        /// </summary>
        public static string ReportMessage {
            get {
                return ResourceManager.GetString("ReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł jest wymagany!.
        /// </summary>
        public static string RequiredTitle {
            get {
                return ResourceManager.GetString("RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-A.
        /// </summary>
        public static string ReverseAlphabetical {
            get {
                return ResourceManager.GetString("ReverseAlphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Względem daty ↓.
        /// </summary>
        public static string ReverseDate {
            get {
                return ResourceManager.GetString("ReverseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz zmiany.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj zadanie.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż wszystkie.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcje sortowania:.
        /// </summary>
        public static string SortingOptions {
            get {
                return ResourceManager.GetString("SortingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podsumowanie.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygenerowano podsumowanie w formacie {0}.
        /// </summary>
        public static string SummaryMessage {
            get {
                return ResourceManager.GetString("SummaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag:.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Zadania.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonane.
        /// </summary>
        public static string TaskStatus_Done {
            get {
                return ResourceManager.GetString("TaskStatus_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewykonane.
        /// </summary>
        public static string TaskStatus_NotDone {
            get {
                return ResourceManager.GetString("TaskStatus_NotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł:.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zbliżające się terminy wykonania zadań:.
        /// </summary>
        public static string UpcomingTasksTitle {
            get {
                return ResourceManager.GetString("UpcomingTasksTitle", resourceCulture);
            }
        }
    }
}
